version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Running tests'
          command: npm run test
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: 'Running lint'
          command: npm run lint

workflows:
  node-tests:
    jobs:
      - lint
      - test